### ISSUE TITLE
Crash on update 

### ISSUE THREAD

**Issue by GeneralTanker** [nicolas-lang/factorio.InserterCranes#1]
I updated this mod to 0.0.4 it crashed on startup. Downgrading to 0.0.3 makes it work again.

https://imgur.com/RjYSbk3

**Comment by nicolas-lang** [comment]
it is probably related to "expensive/normal" ... got a fix ready but it still needs testing

**Comment by GeneralTanker** [comment]
0.0.5 has fixed the issue so this can be closed.

**Comment by nicolas-lang** [comment]
ty for the report, I am happy 0.0.5 fixed the issue :-)

**Comment by Mernom** [comment]
The way I typically handle the formats is
for _, entry in pairs ({prototype, prototype.normal, prototype.expensive}) do
  *code*
end

**Comment by nicolas-lang** [comment]
Good Idea, never thought about that... Thanks (again!)
