### ISSUE TITLE
The crane does not use its full load capacity

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [nicolas-lang/factorio.InserterCranes#7]
I installed the mod and used cranes to load Space Exploration ores onto trains and noticed that despite the size of the crane bundle of 198 +1, but still takes an item equal to her bundle in the screenshot of berylia with a bundle size of 50.

![image](https://user-images.githubusercontent.com/46845681/187679880-7b3a3266-d180-418f-a325-cfa9324b4f25.png)

![image](https://user-images.githubusercontent.com/46845681/187679923-13a4f3b9-f40b-4571-b601-a45d8986497c.png)

Is something not working correctly or do I not understand something?

**Comment by nicolas-lang** [comment]
It is a limitation of the "stack" inserter prototype in factorio: It can only move up to 1 single stack of items.
If the stack-size of an item is less then the inserter's capacity it would make more sense to use smaller inserters.

This is the reason for the mod providing a wide 6x2 and a 2x2 non-wide crane.
The throughput is calculated based on the crane's footprint, three 2x2 cranes have a similar item-transfer-capacity as a 6x2 wide crane but each of them has only 1/3 of the hand-size.
